import {
  StyleFunctionProps,
  createMultiStyleConfigHelpers,
} from '@chakra-ui/react';

const helpers = createMultiStyleConfigHelpers([
  // KanbanBoard
  'wrapper',
  'columnList',
  // Column
  'column',
  'buttonAddTask',
  'columnContent',
  'badgeTitle',
  // Card
  'card',
  'icons',
  'badgeDate',
  'iconButton',
  'avatar',
  // EmptyTasksList
  'wrapperEmptyTasksList',
  'boxH1',
  'boxSpan',
  'link',
]);

export const Flex = helpers.defineMultiStyleConfig({
  variants: {
    kanbanBoard: ({ columnsLength }: StyleFunctionProps) => ({
      wrapper: {
        m: '10px auto',
        w: '100%',
        maxW: '1140px',
        minH: '703px',
        p: '22px 57px 10px 70px',
        shadow: '0px 0px 10px 10px rgba(0,0,0,0.3)',
        borderRadius: 10,
        bg: '#f5f5fa',
        overflowX: columnsLength > 3 ? 'auto' : 'hidden',
        overflowY: 'auto',
      },
      columnList: {
        w: '100%',
        justifyContent: 'space-between',
      },
    }),
    column: ({ tasksLength, colorBadge, color }: StyleFunctionProps) => ({
      column: {
        flexDirection: 'column',
        w: '100%',
        minW: '332px',
        h: '649px',
        mr: '8px',
      },
      columnContent: {
        height: tasksLength ? 'fit-content' : '170px',
        flexDirection: 'column',
        borderRadius: '10px',
        position: 'relative',
      },
      buttonAddTask: {
        minW: '320px',
        w: '100%',
        h: '52px',
        minH: '52px',
        border: 'dotted',
        borderColor: '#CFDBD5',
        borderRadius: 5,
        bg: '#fff',
        borderWidth: '2px',
        mb: '7px',
      },
      badgeTitle: {
        borderRadius: 15,
        bgColor: colorBadge,
        px: '15px',
        py: '2px',
        variant: 'solid',
        color: color,
        textTransform: 'none',
        cursor: 'default',
        maxW: '270px',
        whiteSpace: 'wrap',
      },
    }),
    card: {
      card: {
        position: 'relative',
        w: '100%',
        minW: '320px',
        minH: '102px',
        borderRadius: '10px',
        p: '18px 23px 23px 15px',
        color: '#000',
        mb: '7px',
        cursor: 'pointer',
        justifyContent: 'space-between',
        flexDirection: 'column',
      },
      icons: {
        display: 'flex',
        justifyContent: 'space-between',
        h: '24px',
      },
      badgeDate: {
        variant: 'solid',
        bg: '#F5F5FA',
        w: 'fit-content',
        px: 2,
        fontSize: '12px',
        fontWeight: 'bold',
        alignItems: 'center',
        borderRadius: 10,
        color: '#5F646D',
        justifyContent: 'center',
        display: 'flex',
        textTransform: 'lowercase',
      },
      iconButton: {
        position: 'absolute',
        color: 'transparent',
        bg: 'transparent',
        w: 'fit-content',
        _hover: {
          bg: 'transparent',
        },
        zIndex: 1,
        paddingInline: 0,
        h: '20px',
        minW: '20px',
        top: '8px',
        right: '8px',
      },
      avatar: {
        ml: '2px',
        w: '24px',
        h: '24px',
        borderRadius: '50px',
        shadow: '0px 0px 6px 1px rgba(0,0,0,0.2)',
      },
    },
    emptyTasksList: {
      wrapperEmptyTasksList: {
        mx: 'auto',
        h: 'fit-content',
        mt: '100px',
        flexDirection: 'column',
        fontFamily: 'Roboto Flex',
      },
      boxH1: {
        fontWeight: '800',
        fontSize: '42px',
        lineHeight: '56px',
        mt: '50px',
        mx: 'auto',
        mb: '6px',
      },
      boxSpan: {
        fontWeight: '400',
        fontSize: '14px',
        lineHeight: '21px',
        mx: 'auto',
      },
      link: {
        fontWeight: '700',
        fontSize: '14px',
        lineHeight: '21px',
        mx: 'auto',
        color: '#0052FF',
        w: '144px',
        h: '52px',
      },
    },
  },
});
